### ISSUE TITLE
Compiling lepton from scratch

### ISSUE THREAD

**Issue by tpetricek** [slithiaote/lepton#2]
My understanding is that `lepton.nw` is the implementation of Lepton in itself which, when processed through Lepton, will produce a `tex` file with description and an OCaml source code that can then be compiled to get Lepton running. Is that right?

However, I could not figure out how to actually bootstrap the process. The repository has `lepton.bin` binary, but I don't know how to run this (neither on Windows, nor using the Ubuntu bash on Windows) and I also think it's wrong to have binary in the repo.

I think it would be better if you included OCaml source code for bootstrapping, perhaps with `Makefile` or some other easy to run script that will produce a compile binary for my current platform. Then I could run that to process `lepton.mw` and get my own build. However, given the current setup, I was not able to run anything.

**Comment by slithiaote** [comment]
Thank you for your comments

Your understanding is mostly correct. When processed through Lepton, lepton.nw will produce the OCaml source code **and** compile it. You should obtain a new binary. As such, lepton.nw is in itself a kind of Makefile or script that is easy to run, albeit you need a first implementation of Lepton.

The executable is for linux systems and should work on 32bit and 64bit systems. It won't work on Windows. I am unsure about Ubuntu bash, but I believe it should work if you write the command in a terminal, or at least give you a useful error. Were you able to run the command `./lepton.bin lepton.nw -o lepton.tex` in Section 3 of `lepton.pdf` (the rendered version of `lepton.nw`) ? 

While I agree that distributing binaries is wrong in general, I think that Lepton defines a "new source code format", and is similar to compilers such as gcc in that respect. As far as I understand, you have to provide a binary implementation of the compiler in order to compile its source code.

**Comment by tpetricek** [comment]
I get the following when I try to run the above command:

```
root@lipwig:/mnt/c/Tomas/Public/tpetricek/lepton# chmod +x lepton.bin
root@lipwig:/mnt/c/Tomas/Public/tpetricek/lepton# ./lepton.bin
-bash: ./lepton.bin: cannot execute binary file: Exec format error
```

That said, I think you should be able to avoid distributing binaries. If you provide the OCaml source code generated from your `nw` source file, together with a Makefile, then I think that would make the bootstrapping a lot easier (and it would enable you to support multiple platforms).

**Comment by slithiaote** [comment]
I believe that today's commit should fix this issue, I switched to a source-based distribution.

I initially thought that command interpretation with Lepton could only be available on Linux with the current code base, so distributing a linux binary was acceptable. The possibility to use Lepton on Windows Subsystem for Linux tips the balance in favor of compiling from source.

**Comment by tpetricek** [comment]
Looking at the current version, I'm much happier about the new approach!

That said, just running `make.sh` does not yet work for me - presumably, because I need to install some dependencies. Is this documented somewhere?

**Comment by slithiaote** [comment]
Apart from a standard installation of the Ocaml compiler, there are no dependencies for running make.sh. No external libraries are required.
Can you check that `ocamllex` and `ocamlopt` are installed ? I just recall that some Linux distributions do not install the full OCaml system by default.

**Comment by tpetricek** [comment]
No, I don't think I have OCaml installed - but I think that instructions like these should be included in the project readme or building guide.

**Comment by slithiaote** [comment]
Section "3 Obtaining the software", page 8 of the `lepton.pdf` documentation describes how to compile the source files with Ocaml to obtain the executable, as well as the expected output of `make.sh`. The bootstrapping instructions are provided in the same section.
Are these insufficient in your opinion ?

**Comment by tpetricek** [comment]
I think these are sufficient for a personal project, but not for a high-quality easy to use open source software published in JOSS. I just had a quick look at the last 5 projects accepted to JOSS and they all either have instructions directly in README or they have a direct link to documentation which has installation instructions.

**Comment by yochannah** [comment]
@slithiaote I note you've made a nice readme update. I have a few comments:

- I installed ocaml and tried run the [setup script](https://github.com/slithiaote/lepton#installation). Is this right?

```bash
chmod +x make.sh
./make.sh
``` 

This output the following to the console. I'm not sure if it worked?

```bash
101 states, 393 transitions, table size 2178 bytes
1974 additional bytes used for bindings
File "lexer.mll", line 73, characters 20-35:
Warning 10: this expression should have type unit.
File "lexer.mll", line 42, characters 57-58:
Warning 26: unused variable s.
File "lexer.mll", line 43, characters 63-64:
Warning 26: unused variable s.
File "lexer.mll", line 42, characters 33-34:
Warning 26: unused variable h.
File "lexer.mll", line 42, characters 33-34:
Warning 26: unused variable h.
File "lexer.mll", line 42, characters 33-34:
Warning 26: unused variable h.
File "lexer.mll", line 42, characters 57-58:
Warning 26: unused variable s.
File "lexer.mll", line 45, characters 27-28:
Warning 26: unused variable b.
File "lexer.mll", line 45, characters 68-69:
Warning 26: unused variable s.
```

When I run `lepton` in the console after this, my console says `command not found: lepton`

Any suggestions - am I doing something wrong? 

I'm still working on trying the bootstrapping instructions and may have further comments :)

**Comment by slithiaote** [comment]
The warnings are expected, I believe the pattern-matching code is easier to read with them.

`make.sh` generates `lepton.bin`, so you should run `./lepton.bin` if you want to use the program. For bootstrapping, you should rename the executable. I have just updated the documentation and tested on my computer.

**Comment by slithiaote** [comment]
Closing because no update in more than one year
